content:
  - name: tiers
    label: Tiers
    path: tiers
    filename: '{primary}.json'
    format: json
    type: collection
    view:
      layout: tree
      sort: [ id ]
      fields: [ id, rank, text ]
      primary: id
    fields:
      - name: id
        label: ID
        type: string
        pattern: ^[a-z][a-z0-9\-]+[a-z]$
      - name: rank
        label: Rank
        type: select
        options:
          values: ["S", "A", "B", "C", "D", "F", "O"]
      - name: title
        label: Title
        type: string
      - name: text
        label: Text for entry
        type: rich-text
        options:
          rows: 30

