content:
  - name: chris-nolan-movies
    label: Christopher Nolan Movies
    path: tiers/chris-nolan-movies
    filename: '{primary}.json'
    format: json
    type: collection
    view:
      fields: [ id, rank, text]
      primary: id
    fields:
      - name: id
        label: ID
        type: string
        pattern: ^[a-z][a-z0-9\-]+[a-z]$
      - name: rank
        label: Rank
        type: select
        options:
          values: ["S", "A", "B", "C", "D", "F", "O"]
      - name: text
        label: Text for entry
        type: rich-text
        options:
          rows: 30

